### ISSUE TITLE
Move transformations from article app into ingest

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-es-interface#196]
Transforms within the article app that are unopinionated about presentation should be performed as content is ingested to prevent repeated work.

- [x] https://github.com/Financial-Times/next-article/blob/master/server/transforms/relative-links.js
- [x] https://github.com/Financial-Times/next-article/blob/master/server/transforms/replace-ellipses.js
- [x] https://github.com/Financial-Times/next-article/blob/master/server/transforms/replace-hrs.js

We could also consider:

- [x] Removing newlines I.E. `/\r?\n|\r/`
- [x] Removing redundant elements such as empty paragraphs or line breaks between paragraphs

**Comment by wheresrhys** [comment]
Following a meeting with the data team it'd be great if these transforms could also output statistics on the type of content contained in an article in something like a `contentStats` property.
