### ISSUE TITLE
Deprecate read endpoints

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-es-interface#197]
The web interface and some of its endpoints are likely reaching the end of their usefulness. Applications [using these endpoints are few](https://github.com/search?utf8=%E2%9C%93&q=next-es-interface.ft.com+user%3AFinancial-Times&type=Code&ref=searchresults) and there is probably little reason they cannot use Elasticsearch or CAPI directly instead of this middleman.

Endpoints with potential to be removed: 

- [ ] /things
- [ ] /content
- [ ] /brand and /sections and /authors
- [ ] /oldest

**Comment by matthew-andrews** [comment]
i think this is a bit ambitious………
