### ISSUE TITLE
Decorate videos with title and description

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-es-interface#201]
We get links from CAPI as part of the article body:

```
<a data-asset-type=\"video\" data-embedded=\"true\" href=\"http://video.ft.com/4575033581001\"></a>
```

But this lacks some information we'd like that is available from the Brightcove API:

```
http://api.brightcove.com/services/library?command=find_video_by_id&video_id=4575033581001&token=<token>
```

**Comment by andygnewman** [comment]
@i-like-robots Given we have now implemented title on video in article (though admittedly not in ES), can we close this?

**Comment by i-like-robots** [comment]
I think we should still do this, I think if we do so we can get rid of a lot of code elsewhere (maybe an entire app).

**Comment by matthew-andrews** [comment]
what's the plan here chaps?

**Comment by i-like-robots** [comment]
I've gotten cold feet on this a little TBH... I think all we'd want is a title.

**Comment by matthew-andrews** [comment]
👌 👣
