### ISSUE TITLE
Subheadings for concepts

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-es-interface#202]
Could we put a small subhead tagline to describe what some of these esoteric brand names mean. e.g. “The Sage and the  Shrink” - Philosopher Julian Baggini and psychotherapist Antonia Macaro help on how to live. (from pauloneillft )

**Comment by i-like-robots** [comment]
I guess the new brands API covers this =] 

https://github.com/Financial-Times/next-stream-page/blob/8f36e311316279b33f5a3bead02672797ddf4313/views/partials/sub-header.html#L25-L30

**Comment by i-like-robots** [comment]
Can this be closed?

**Comment by andygnewman** [comment]
Yes, I think that you are right that the work done on brand and people / authors API for taglines and descriptions covers this suggestion.
