### ISSUE TITLE
Podcast ‘sections’ should be ‘brands’

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-es-interface#217]
i.e. all these:-

- Listen to Lucy
- FT Money Show
- FT Connected Business
- FT News
- FT Banking Weekly
- FT World Weekly
- FT Arts
- FT Alphachat
- FT Hard Currency
- FT Big Read
- FT UK General Election 2015
- FT Investigations
- Copenhagen Summit podcast
- FT Digital Business: Managing Intelligence
- FT Digital Business with Peter Whitehead
- FT Emerging Markets Weekly podcast
- FT Energy Weekly podcast
- FT House and Home podcast
- FT Management podcast
- FT Science podcast
- FT UK General Election 2010 podcast
- Martin Wolf podcast
- Robin Robertson podcast
- Stephen Fry and Lady Gaga podcast

**Comment by i-like-robots** [comment]
These tags were created for us just a few months ago, I don't know which taxonomy they sit in under CAPI v1... possibly none as they won't be used there.

**Comment by matthew-andrews** [comment]
Meh, can fix this when podcasts go into the Content API proper.
