### ISSUE TITLE
Search suggestiosn should include podcasts

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-es-interface#218]
https://next-es-interface.ft.com/tmes/sections

**Comment by matthew-andrews** [comment]
Don't do this until this is done:- https://github.com/Financial-Times/next-tme-search-api/issues/35

**Comment by i-like-robots** [comment]
If search suggestions are migrated to use the tag facets API this can be ticked off http://tag-facets-api.ft.com/?partial=podcast
