### ISSUE TITLE
Tidy up IAMs

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-es-interface#321]
REMOVE THE FOLLOWING ACCOUNTS FROM AWS:-
next-search-read-ab
next-search-read-propensity-api
next-search-read-myft-api
next-search-read-login-logout
next-search-read-graphite-dashboard
next-search-read-service-worker
next-search-read-api-user-prefs
next-search-read-preflight-requests
next-search-read-opt-in-out
next-search-read-ijento
next-search-read-es-interface
next-search-read-errors
next-search-read-session-service
next-search-read-interactives
next-search-read-spoor-consumer
next-search-read-toggler
next-search-read-user-feedback
next-search-read-clippings-redirector
next-search-read-config-vars
next-search-read-beacon-dashboard
next-search-read-opt-out-form
next-search-read-brightcove-proxy-api
next-search-read-markets-proxy-api

CREATE NEW ACCOUNT:-
next-search-read-graphql-api

**Comment by i-like-robots** [comment]
Is this done?

**Comment by matthew-andrews** [comment]
umm maybe not

**Comment by i-like-robots** [comment]
@sjparkinson ?
