### ISSUE TITLE
Flag content types in articles when ingested (eg. hasVideo)

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-es-interface#354]
Should flag various aspects of content when ingested;

eg.
video
podcast
big number
quote etc.

So we can then use this in finding rich articles etc. from streams

**Comment by matthew-andrews** [comment]
In the future™ we will have podcasts and videos appearing in streams (or in the case of podcasts, in more streams) in their own right.  We should make sure the product/design teams make future proof decisions.  E.g. how should you distinguish between something that indicates to a user that an article _contains_ a video versus _is_ a video.

cc @mmockett

**Comment by mmockett** [comment]
Definitely!

**Comment by sumeetadur** [comment]
"isVideo" is sometimes used in the [highlighted card](https://github.com/Financial-Times/next-stream-page/blob/master/shared/components/highlighted-card/index.js) in [stickies](https://github.com/Financial-Times/next-stream-page/blob/master/shared/components/stickies/index.js) and [featured content](https://github.com/Financial-Times/next-stream-page/blob/master/shared/components/featured-content/index.js)

**Comment by i-like-robots** [comment]
fixed in #738
