### ISSUE TITLE
new `url` property …

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-es-interface#432]
… which will (initially) be, for normal articles:-

```
/content/<uuid>
```

but for ftalphaville articles will be the original ftalphaville url (because we shouldn't be serving it on Next)

```
http://ftalphaville.ft.com/2016/05/12/2161488/ft-opening-quote-60/
```

eventually this will contain the vanity url for articles.

cc @TheoLeanse @andygnewman

[i think `webUrl` should eventually be deprecated 😁]

**Comment by matthew-andrews** [comment]
question:-

should the next url use `https://www.ft.com/content/<uuid>` or `/content/<uuid>` 💭

**Comment by andygnewman** [comment]
The former is what it will be eventually and will correctly redirect in the meantime, the latter is how we generally use it today though and gives us flexibility. But I would opt for the former I think.

**Comment by TheoLeanse** [comment]
not sure I know enough about es-interface but would guess that the full url would be marginally more useful for the apps that consume it? although wonder how many other cases are there where the host is not `www.ft.com`?

**Comment by matthew-andrews** [comment]
i think it should be the former, although it will make rendering those links on Next apps a little more complex… you'll need to do `url.replace('https://www.ft.com/', '')` every time.

**Comment by matthew-andrews** [comment]
but the former is right because es is in use by other apps on other domains
