### ISSUE TITLE
Add fine grained controls to ES access

### ISSUE THREAD

**Issue by richard-still-ft** [Financial-Times/next-es-interface#439]
Paths for read users:

- `arn:aws:es:eu-west-1:027104099916:domain/nextcontent/[index]/_search`
- `arn:aws:es:eu-west-1:027104099916:domain/nextcontent/[index]/_mget`

Power users should have everything @matthew-andrews @i-like-robots anything else?

**Comment by richard-still-ft** [comment]
Also lock down the health endpoint

**Comment by i-like-robots** [comment]
I think that's OK, other legit endpoints (E.G.`_all`,  `_stats` or `_analyze `) are `GET` requests.

All others are 'power user', E.G. `_scroll`, `_bulk`, `_alias` and `_snapshot`.

**Comment by i-like-robots** [comment]
This has been done, hasn't it?

**Comment by matthew-andrews** [comment]
I think so.
