### ISSUE TITLE
Kinesis stream for ingests and deletions [ EU only ] 

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-es-interface#486]
- [x] CloudFormation
- [x] EU-only
- [x] Publish an events to it on ingest or delete
- [x] Advertise the Kineses stream on the es-interface README.md
- [x] BONUS POINTS: distinguish creates from updates
- [x] Add tags to the Kinesis stream to conform to the FT Tagging policy
- [ ] 🎉

**Comment by richard-still-ft** [comment]
I have a personal preference for a queue rather than SNS but not hugely bothered. It just means that consumer of these events can afford to be down and wont miss out on anything.

**Comment by TheoLeanse** [comment]
Could SNS retry policy stuff be useful in case of consumer downtime?

**Comment by phamann** [comment]
I'd suggest a Kinesis stream over an SNS topic for the above reasons. Data can be retained for 7 days and consumed from any point in the queue and allows multiple consumers.

**Comment by matthew-andrews** [comment]
i've never used either so completely happy to go with the wisdom of the wiser people in this thread.

**Comment by richard-still-ft** [comment]
👍
