### ISSUE TITLE
Kinesis permissions

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/next-es-interface#502]
Do we need a separate `kinesis:*` section in `AccessPolicies `? I was playing around with it and got `User: arn:aws:iam::027104099916:user/google-amp-staging.prod is not authorized to perform: kinesis:DescribeStream on resource: arn:aws:kinesis:us-east-1:027104099916:stream/nextContentChangelog`.

**Comment by matthew-andrews** [comment]
you will need to have some kinesis permissions - ideally read only ones

**Comment by quarterto** [comment]
I was more asking how do we get kinesis permissions?

**Comment by matthew-andrews** [comment]
ah…… #cloud-enablement on slack / salesforce
