### ISSUE TITLE
Content Model Debt - primaryTag

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-es-interface#526]
Storing primary tag

A few considerations;

### Excluding certain taxonomies
On the home page (and in top stories on streams) certain taxonomies ('organisations', 'regions', 'people') are excluded from being in the primary tag. So if the primary theme were a region, primary tag would fallback to primary section (if available).

This is for editorial reasons - usually that the value of that taxonomy would usually be in the headline.
Whereas at the top of an article / in the stream list we don't do those exclusions.

Proposed solution:
Have both a standard version (`primaryTag`) and an editorial version (`primaryTagEditorial`)

### Inclusion of primary brand in the primary tag 
Some implementations have the inclusion of primary brand as the third element in the hierarchy (after theme and section). Though rare that it gets used as primary tag as I think primary section is mandatory.

Proposed solution:
Retain primary brand as the third element in the hierarchy.

### Data model for primary tag

primaries (theme, section, brand) are stored as properties of the relevant metadata.

The primaryTag(s) could be either stored as;
- top level properties that duplicate that specific metadata
```
    primaryTag: 
        {
            idV1: "TnN0ZWluX1BOX1BvbGl0aWNpYW5fNTYx-UE4=",
            prefLabel: "Theresa May",
            taxonomy: "people",
            attributes: [ ],
            url: "https://www.ft.com/theresa-may"
        },
    primaryTagEditorial: 
        {
            idV1: "Nw==-U2VjdGlvbnM=",
            prefLabel: "UK Business & Economy",
            taxonomy: "sections",
            attributes: [ ],
            url: "https://www.ft.com/world/uk/business-economy"
        }
```
or
- further properties of the existing metadata
```
    {
        idV1: "TnN0ZWluX1BOX1BvbGl0aWNpYW5fNTYx-UE4=",
        prefLabel: "Theresa May",
        taxonomy: "people",
        primary: "theme",
        primaryTag: true,
        attributes: [ ],
        url: "https://www.ft.com/theresa-may"
    },
    {
        idV1: "Nw==-U2VjdGlvbnM=",
        prefLabel: "UK Business & Economy",
        taxonomy: "sections",
        primary: "section",
        primaryTagEditorial: true,
        attributes: [ ],
        url: "https://www.ft.com/world/uk/business-economy"
    }
```

Proposed solution:
Add further properties to the existing metadata - avoids duplication of content.

**Comment by i-like-robots** [comment]
I like the idea of adding the property instead of a separate field. I'm less keen on having the distinction between primary tag and an editorial primary tag... it all begins to get a bit woolly.

Perhaps adjusting the terminology, `primaryTag` and `secondaryTag` perhaps?

**Comment by i-like-robots** [comment]
We can then drop the `primary` field after because it no longer has any purpose

**Comment by i-like-robots** [comment]
I'd also add a check for `primaryTag` to the sanity check

**Comment by andygnewman** [comment]
Yeah, the naming was the difficult bit. I was trying to convey something that had an element of 'interference' in it's calculation rather than the 'purity' of `primaryTag`. `secondaryTag` could work or perhaps in line with where we're going with cards (which is the use case for this other tag) we could do `teaserTag`?

**Comment by andygnewman** [comment]
Just remembered a usage of the primary field => article more-ons, use the first two primaries in the hierarchy, so may need to retain for now.

**Comment by i-like-robots** [comment]
Also included in https://github.com/Financial-Times/next-es-interface/pull/534
