### ISSUE TITLE
Fix messaging in the republish tool

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/next-es-interface#591]
Apparently the `Doin' stuff...` message was displaying for an hour although the ingest was completed successfully.

![pasted image at 2016_11_10 09_12](https://cloud.githubusercontent.com/assets/11544418/20172977/32eda8fa-a72f-11e6-9741-ff85b35e175b.png)

**Comment by i-like-robots** [comment]
Unable to re-create this issue...
