### ISSUE TITLE
3 periods being encrypted as ellipsis for img src 

### ISSUE THREAD

**Issue by laurent-muchacho** [Financial-Times/next-es-interface#599]
In the body of article (uuid c2acb8ef-bc5b-3763-a493-a24e1e6b3406) there is an image src (https://ftalphaville-cdn.ft.com/wp-content/uploads/2016/11/15003720/Negative_term_premi-umm...-line_chart-ft-web-themelarge-2048x1152-1_2048x1152-590x332.png) that contains 3 periods and those are being replaced by %E2%80%A6

Doing this break the image from being resolved https://ftalphaville-cdn.ft.com/wp-content/uploads/2016/11/15003720/Negative_term_premi-umm%E2%80%A6-line_chart-ft-web-themelarge-2048x1152-1_2048x1152-590x332.png

Many thanks

**Comment by i-like-robots** [comment]
For context - when uploading files to Wordpress it maintains the original filename and shortens it if it is too long.

¯\_(ツ)_/¯
