### ISSUE TITLE
v2 notifications handling should remember links.href

### ISSUE THREAD

**Issue by davidlintonattheft** [Financial-Times/next-es-interface#769]
NES currently polls v2 notifications with a freshly minted `since` parameter every time.
This isn't recommended as it risks missing notifications.

Instead, it should look at the `links.href` property in the notifications response (strictly ,the one whose `links.rel` is `next`) and use that URL for the next request, even across polling jobs.

see [docs](https://developer.ft.com/docs/license_quick_start/datamininglicense
)

**Comment by i-like-robots** [comment]
Am I correct in assuming that the V2 notifications feed _is not_ paginated (this is what the current process is setup for)?

**Comment by i-like-robots** [comment]
Also is this true for V1 or should we continue to use a timestamp?

**Comment by davidlintonattheft** [comment]
The v2 feed is paginated at 200, there are parameters in the `links.href` that ensure you get the right next page. But always use the complete `links.href` rather than interpreting it. You can stop when there are no notifications in the response.

**Comment by davidlintonattheft** [comment]
We haven't changed the v1 feed, I don't know what corner case might exist there.

**Comment by i-like-robots** [comment]
Because the `links` field is an array can it contain multiple links that are differentiated by their `rel` property? I.E. is there a difference between links for "next page" and  "next time you poll"?

**Comment by davidlintonattheft** [comment]
Theoretically yes it could contain more links, but `next` serves for both "next page" and "next time you poll" as there's not really any difference, both are "continue this list"
