### ISSUE TITLE
Odd organisation redirect

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/next-es-interface#95]
From `HSBC Holdings PLC` to `Silom Ltd.`, e.g.

 * search for `hsbc`
 * click on any of the `HSBC Holdings PLC` tag links
 * notice you end up on the `Silom Ltd.` organisation page

**Comment by matthew-andrews** [comment]
seems ok now, can you double check?

**Comment by ironsidevsquincy** [comment]
Looks ok to me
